{% set name = "mailchecker" %}
{% set version = "6.0.21" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mailchecker-{{ version }}.tar.gz
  sha256: b4c668403bc32cfaa96e7585914778429c9d748e558d2e6abb599b12f0997904

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - MailChecker
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/FGRibreau/mailchecker
  summary: Cross-language email validation. Backed by a database of thousands throwable email providers.
  license: MIT
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - pmrowla
    - shcheklein
