{% set name = "mailchecker" %}
{% set version = "6.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mailchecker-{{ version }}.tar.gz
  sha256: 411cac9ad2a8e4a5d7015732431d96c2ec324943fcbc037f82a5d69a0a0e3e6a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - MailChecker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/FGRibreau/mailchecker
  summary: Cross-language email validation. Backed by a database of thousands throwable email providers.
  license: MIT
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - pmrowla
    - efiop
    - shcheklein
