{% set name = "mailchecker" %}
{% set version = "6.0.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mailchecker-{{ version }}.tar.gz
  sha256: 902d482d1b5d4106edd2eecc067340c68b6ce4e24790964381384f67d35b9e55

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - MailChecker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/FGRibreau/mailchecker
  summary: Cross-language email validation. Backed by a database of thousands throwable email providers.
  license: MIT
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - pmrowla
    - efiop
    - shcheklein
